/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rugbyworldcup;

import java.io.Serializable;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gilbertocaobianco
 */
public class RugbyWorldCupGUI extends javax.swing.JFrame {
    
    ArrayList<Countries> countries;

    /**
     * Creates new form RugbyWorldCupGUI
     */
    public RugbyWorldCupGUI() {
        initComponents();
        
        countries = new ArrayList<> ();
        
        dublinLB.setVisible(false);
        corkLB.setVisible(false);
        avivaLB.setVisible(false);
        crokeLB.setVisible(false);
        
        parisLB.setVisible(false);
        lyonLB.setVisible(false);
        parcDesPrincesLB.setVisible(false);
        parcOlympiqueLyonnaisLB.setVisible(false);
        
        johannesburgLB.setVisible(false);
        capeTownLB.setVisible(false);
        ellisParkStadiumLB.setVisible(false);
        capeTownStadiumLB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        welcomeJL = new javax.swing.JLabel();
        irelandRB = new javax.swing.JRadioButton();
        franceRB = new javax.swing.JRadioButton();
        southAfricaRB = new javax.swing.JRadioButton();
        cityJL = new javax.swing.JLabel();
        stadiumJL = new javax.swing.JLabel();
        option1JL = new javax.swing.JLabel();
        option2JL = new javax.swing.JLabel();
        option3JL = new javax.swing.JLabel();
        option1TF = new javax.swing.JTextField();
        option2TF = new javax.swing.JTextField();
        option3TF = new javax.swing.JTextField();
        threeJL = new javax.swing.JLabel();
        twoJL = new javax.swing.JLabel();
        oneJL = new javax.swing.JLabel();
        dublinLB = new javax.swing.JLabel();
        corkLB = new javax.swing.JLabel();
        avivaLB = new javax.swing.JLabel();
        crokeLB = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        viewAllVotesBTN = new javax.swing.JButton();
        parisLB = new javax.swing.JLabel();
        lyonLB = new javax.swing.JLabel();
        johannesburgLB = new javax.swing.JLabel();
        parcDesPrincesLB = new javax.swing.JLabel();
        parcOlympiqueLyonnaisLB = new javax.swing.JLabel();
        ellisParkStadiumLB = new javax.swing.JLabel();
        capeTownLB = new javax.swing.JLabel();
        capeTownStadiumLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeJL.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        welcomeJL.setText("Welcome to the Rugby World Cup 2023");

        buttonGroup1.add(irelandRB);
        irelandRB.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        irelandRB.setText("Ireland");
        irelandRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irelandRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(franceRB);
        franceRB.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        franceRB.setText("France");
        franceRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franceRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(southAfricaRB);
        southAfricaRB.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        southAfricaRB.setText("South Africa");
        southAfricaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southAfricaRBActionPerformed(evt);
            }
        });

        cityJL.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        cityJL.setText("Cities");

        stadiumJL.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        stadiumJL.setText("Stadiums");

        option1JL.setText("First Choice");

        option2JL.setText("Second Choice");

        option3JL.setText("Third Choice");

        option1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1TFActionPerformed(evt);
            }
        });

        option2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2TFActionPerformed(evt);
            }
        });

        option3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3TFActionPerformed(evt);
            }
        });

        threeJL.setText("Three Points");

        twoJL.setText("Two Points");

        oneJL.setText("One Point");

        dublinLB.setText("Dublin");

        corkLB.setText("Cork");

        avivaLB.setText("Aviva Stadium ");

        crokeLB.setText("Croke Stadium");

        submitBTN.setText("Submit");

        viewAllVotesBTN.setText("View All Votes");

        parisLB.setText("Paris");

        lyonLB.setText("Lyon");

        johannesburgLB.setText("Johannesburg");

        parcDesPrincesLB.setText("Parc Des Princes");

        parcOlympiqueLyonnaisLB.setText("Parc Olympique Lyonnais");

        ellisParkStadiumLB.setText("Ellis Park Stadium");

        capeTownLB.setText("Cape Town");

        capeTownStadiumLB.setText("Cape Town Stadium");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(irelandRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(franceRB)
                .addGap(177, 177, 177)
                .addComponent(southAfricaRB)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeJL)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(option3JL)
                    .addComponent(option2JL)
                    .addComponent(option1JL))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewAllVotesBTN)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(option3TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(option1TF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(option2TF, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twoJL)
                            .addComponent(threeJL)
                            .addComponent(oneJL))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cityJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stadiumJL)
                        .addGap(180, 180, 180))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dublinLB)
                            .addComponent(corkLB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avivaLB)
                            .addComponent(crokeLB))
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capeTownLB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lyonLB)
                                    .addComponent(parisLB)
                                    .addComponent(johannesburgLB))
                                .addGap(307, 307, 307)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parcDesPrincesLB)
                                    .addComponent(ellisParkStadiumLB)
                                    .addComponent(capeTownStadiumLB)
                                    .addComponent(parcOlympiqueLyonnaisLB))))
                        .addContainerGap(107, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeJL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irelandRB)
                    .addComponent(franceRB)
                    .addComponent(southAfricaRB))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJL)
                    .addComponent(stadiumJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dublinLB)
                    .addComponent(avivaLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corkLB)
                    .addComponent(crokeLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parisLB)
                    .addComponent(parcDesPrincesLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lyonLB)
                    .addComponent(parcOlympiqueLyonnaisLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(johannesburgLB)
                    .addComponent(ellisParkStadiumLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capeTownLB)
                    .addComponent(capeTownStadiumLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1JL)
                    .addComponent(option1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2JL)
                    .addComponent(option2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3JL)
                    .addComponent(oneJL))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBTN)
                    .addComponent(viewAllVotesBTN))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irelandRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irelandRBActionPerformed
        // TODO add your handling code here:
        
        dublinLB.setVisible(true);
        corkLB.setVisible(true);
        avivaLB.setVisible(true);
        crokeLB.setVisible(true);
        
        parisLB.setVisible(false);
        lyonLB.setVisible(false);
        parcDesPrincesLB.setVisible(false);
        parcOlympiqueLyonnaisLB.setVisible(false);
        
        johannesburgLB.setVisible(false);
        capeTownLB.setVisible(false);
        ellisParkStadiumLB.setVisible(false);
        capeTownStadiumLB.setVisible(false);
        
        
        
    }//GEN-LAST:event_irelandRBActionPerformed

    private void option1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1TFActionPerformed

    private void franceRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franceRBActionPerformed
        // TODO add your handling code here:
        
        dublinLB.setVisible(false);
        corkLB.setVisible(false);
        avivaLB.setVisible(false);
        crokeLB.setVisible(false);
        
        parisLB.setVisible(true);
        lyonLB.setVisible(true);
        parcDesPrincesLB.setVisible(true);
        parcOlympiqueLyonnaisLB.setVisible(true);
        
        johannesburgLB.setVisible(false);
        capeTownLB.setVisible(false);
        ellisParkStadiumLB.setVisible(false);
        capeTownStadiumLB.setVisible(false);
    }//GEN-LAST:event_franceRBActionPerformed

    private void southAfricaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southAfricaRBActionPerformed
        // TODO add your handling code here:
        dublinLB.setVisible(false);
        corkLB.setVisible(false);
        avivaLB.setVisible(false);
        crokeLB.setVisible(false); 
        
        parisLB.setVisible(false);
        lyonLB.setVisible(false);
        parcDesPrincesLB.setVisible(false);
        parcOlympiqueLyonnaisLB.setVisible(false);
        
        johannesburgLB.setVisible(true);
        capeTownLB.setVisible(true);
        ellisParkStadiumLB.setVisible(true);
        capeTownStadiumLB.setVisible(true);
    }//GEN-LAST:event_southAfricaRBActionPerformed

    private void option2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2TFActionPerformed

    private void option3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbyWorldCupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbyWorldCupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbyWorldCupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbyWorldCupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RugbyWorldCupGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avivaLB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel capeTownLB;
    private javax.swing.JLabel capeTownStadiumLB;
    private javax.swing.JLabel cityJL;
    private javax.swing.JLabel corkLB;
    private javax.swing.JLabel crokeLB;
    private javax.swing.JLabel dublinLB;
    private javax.swing.JLabel ellisParkStadiumLB;
    private javax.swing.JRadioButton franceRB;
    private javax.swing.JRadioButton irelandRB;
    private javax.swing.JLabel johannesburgLB;
    private javax.swing.JLabel lyonLB;
    private javax.swing.JLabel oneJL;
    private javax.swing.JLabel option1JL;
    private javax.swing.JTextField option1TF;
    private javax.swing.JLabel option2JL;
    private javax.swing.JTextField option2TF;
    private javax.swing.JLabel option3JL;
    private javax.swing.JTextField option3TF;
    private javax.swing.JLabel parcDesPrincesLB;
    private javax.swing.JLabel parcOlympiqueLyonnaisLB;
    private javax.swing.JLabel parisLB;
    private javax.swing.JRadioButton southAfricaRB;
    private javax.swing.JLabel stadiumJL;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel threeJL;
    private javax.swing.JLabel twoJL;
    private javax.swing.JButton viewAllVotesBTN;
    private javax.swing.JLabel welcomeJL;
    // End of variables declaration//GEN-END:variables
}
